### ISSUE TITLE
no Information visible on map

### ISSUE THREAD

**Issue by mac-arno** [der-On/X-Plane-Flight-Planner#37]
I have no more airports or navs on the map. Just the route is visible with waypoints without airport names. Also the search field top right delivers no search results anymore - just a cycling icon I can see.

**Comment by der-On** [comment]
Please use this URL: http://xplane.anzui.de/flight-planner/

**Comment by mac-arno** [comment]
Thank you very much - this works. I used to use the URL on port 3000.
